[build]
command = 'hugo'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.101.0'


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[[module.imports]]
    path = "ggithub.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5 main"
    disabled = false

    [[module.imports.mounts]]
    source = "testing-hugo-modules"
    target = "content/new-stuff"

